# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'wcisc' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for wcisc
  pod 'SVProgressHUD'

  target 'wciscTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'wciscUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
